name: Dev Build Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  package:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    env:
      DEPLOY_WEBHOOK_URL_DEV: ${{ vars.DEPLOY_WEBHOOK_URL_DEV }}
      DEPLOY_WEBHOOK_TOKEN_DEV: ${{ secrets.DEPLOY_WEBHOOK_TOKEN_DEV }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Cache node modules
        id: cache_node_modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Generate node modules if cache miss
        if: steps.cache_node_modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Compile Typescript
        run: npm run build:dev

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: wiresantoine/wires-frontend:latest,wiresantoine/wires-frontend:dev

      - name: Always deploy on dev environment
        if: github.event_name == 'push'
        run: |
          curl --fail -H "Authorization: ${DEPLOY_WEBHOOK_TOKEN_DEV}" -XGET "${DEPLOY_WEBHOOK_URL_DEV}/frontend?version=${GITHUB_SHA}"
        continue-on-error: true
